language: node_js
node_js:
  - "8"
before_script:
  - npm install -g eslint eslint-config-standard eslint-plugin-import eslint-plugin-node eslint-plugin-promise eslint-plugin-standard
script: eslint js/main.js